version: '3.8'
services:
  npaperless.services:
    image: npaperless.services
    build:
      context: .
      dockerfile: NPaperless.Services/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - npaperless-network
    depends_on:
      - npaperless.dataaccess.sql

  npaperless.webui:
    image: npaperless.webui
    build:
      context: .
      dockerfile: NPaperless.WebUI/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - npaperless-network

  npaperless.dataaccess.sql:
    image: postgres
    environment:
      POSTGRES_DB: npaperless
      POSTGRES_USER: npaperless
      POSTGRES_PASSWORD: npaperless
    ports:
      - "5432:5432"
    networks:
      - npaperless-network
        
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - npaperless-network
  
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "npaperless"
      RABBITMQ_DEFAULT_PASS: "npaperless"
    ports:
      - "5672:5672" # RabbitMQ Server
      - "15672:15672" # RabbitMQ Management Console
    networks:
      - npaperless-network

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "npaperless"
      MINIO_ROOT_PASSWORD: "npaperless123"
    ports:
      - "9000:9000" # Minio API
      - "9090:9090" # Minio Console
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9090"
    networks:
      - npaperless-network

volumes:
  minio_data:

networks:
  npaperless-network:
    driver: bridge
