version: '3.8'
services:
  npaperless.services:
    image: npaperless.services
    build:
      context: .
      dockerfile: NPaperless.Services/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - npaperless-network

  npaperless.webui:
    image: npaperless.webui
    build:
      context: .
      dockerfile: NPaperless.WebUI/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - npaperless-network

  npaperless.dataaccess.sql:
    image: postgres
    environment:
      POSTGRES_DB: npaperless
      POSTGRES_USER: npaperless
      POSTGRES_PASSWORD: npaperless
    ports:
      - "5432:5432"
    networks:
      - npaperless-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: np@np.com
      PGADMIN_DEFAULT_PASSWORD: npaperless
    ports:
      - "80:80"
    networks:
      - npaperless-network

networks:
  npaperless-network:
    driver: bridge
